assert len(decide(1, 3, 1, 1200, True, 1, 2).splitlines()) == 6, "five flags plus the backoff line"
assert decide(1, 3, 1, 1200, True, 1, 2).splitlines()[0] == "Should retry: True", "it failed and attempt 1 is below max 3"
assert decide(1, 3, 1, 1200, True, 1, 2).splitlines()[1] == "Page on-call: False", "retries are left, so nobody is paged yet"
assert decide(1, 3, 1, 1200, True, 1, 2).splitlines()[2] == "Backfill needed: False", "1 day is not more than 1 day"
assert decide(1, 3, 1, 1200, True, 1, 2).splitlines()[3] == "SLA breached: False", "1200s is well under the hour"
assert decide(1, 3, 1, 1200, True, 1, 2).splitlines()[4] == "In window: True", "02:00 is inside the nightly window"
assert decide(1, 3, 1, 1200, True, 1, 2).splitlines()[5] == "Backoff: 60s", "30 * 2 ** 1 while retrying"

assert decide(3, 3, 1, 5400, True, 5, 9).splitlines()[0] == "Should retry: False", "attempt 3 of 3 has no retries left"
assert decide(3, 3, 1, 5400, True, 5, 9).splitlines()[1] == "Page on-call: True", "critical, failed, and out of retries"
assert decide(3, 3, 1, 5400, True, 5, 9).splitlines()[2] == "Backfill needed: True", "5 days since the last success"
assert decide(3, 3, 1, 5400, True, 5, 9).splitlines()[3] == "SLA breached: True", "5400s is over the hour"
assert decide(3, 3, 1, 5400, True, 5, 9).splitlines()[4] == "In window: False", "09:00 is outside the nightly window"
assert decide(3, 3, 1, 5400, True, 5, 9).splitlines()[5] == "Backoff: 0s", "not retrying, so the backoff is zeroed by the flag"

assert decide(1, 3, 0, 100, False, 0, 0).splitlines()[0] == "Should retry: False", "exit code 0 never retries"
assert decide(1, 3, 0, 100, False, 0, 0).splitlines()[1] == "Page on-call: False", "a success pages nobody"
assert decide(1, 3, 0, 100, False, 0, 0).splitlines()[4] == "In window: True", "hour 0 is the start of the window"
assert decide(1, 3, 0, 100, False, 0, 0).splitlines()[5] == "Backoff: 0s", "no retry, no wait"

assert decide(1, 3, 0, 100, False, 9, 3).splitlines()[1] == "Page on-call: True", "9 days without a success pages even on a clean exit"
assert decide(2, 5, 1, 60, False, 0, 5).splitlines()[5] == "Backoff: 120s", "30 * 2 ** 2 on the second attempt"
assert decide(1, 3, 0, 100, False, 0, 6).splitlines()[4] == "In window: False", "hour 6 is outside — the window stops before it"
assert decide(1, 3, 1, 3600, True, 0, 1).splitlines()[3] == "SLA breached: False", "exactly 3600s is not over the SLA"

assert partition_plan(10500, 1000).splitlines()[0] == "Rows: 10500", "the row count is echoed back"
assert partition_plan(10500, 1000).splitlines()[1] == "Full files: 10", "floor division gives the whole files"
assert partition_plan(10500, 1000).splitlines()[2] == "Remainder: 500", "the modulo gives what is left over"
assert partition_plan(10500, 1000).splitlines()[3] == "Files written: 11", "the leftover rows still need a file"
assert partition_plan(9000, 1000).splitlines()[2] == "Remainder: 0", "an exact fit leaves nothing over"
assert partition_plan(9000, 1000).splitlines()[3] == "Files written: 9", "no leftover means no extra file"
assert partition_plan(10, 1000).splitlines()[1] == "Full files: 0", "fewer rows than a file holds"
assert partition_plan(10, 1000).splitlines()[3] == "Files written: 1", "they still have to go somewhere"

assert decode_status(5) == (True, False, True), "bits 1 and 4 are set, bit 2 is not"
assert decode_status(0) == (False, False, False), "a clean run has no bits set"
assert decode_status(7) == (True, True, True), "all three bits set"
assert decode_status(2) == (False, True, False), "only the partial bit"
assert isinstance(decode_status(5)[0], bool), "return real booleans, not the masked integers"

assert identity_check([1], [1]) == (False, True), "two equal lists are not the same object"
assert has_rows([]) == False, "an empty result set"
assert has_rows([1, 2]) == True, "rows came back"
assert has_rows("") == False, "an empty string is falsy too"
assert has_rows({"a": 1}) == True, "a non-empty dict is truthy"
assert isinstance(has_rows([]), bool), "return a real bool, not the result itself"

assert with_default("", "prod") == "prod", "a blank env var falls back"
assert with_default("staging", "prod") == "staging", "a set value wins"
assert with_default(None, "prod") == "prod", "an unset value falls back too"

assert is_allowed("orders", ["orders", "events"]) == True, "the table is on the list"
assert is_allowed("secrets", ["orders", "events"]) == False, "the table is not on the list"
