assert is_balanced("") is True, "an empty string is balanced"
assert is_balanced("(a + b)") is True, "other characters are ignored"
assert is_balanced("{[()]}") is True, "nested brackets are fine"
assert is_balanced("()[]{}") is True, "brackets can sit side by side"
assert is_balanced("(]") is False, "a closer must match its opener"
assert is_balanced("(()") is False, "an unclosed bracket is unbalanced"
assert is_balanced(")(") is False, "a closer before any opener is unbalanced"
assert is_balanced("([)]") is False, "brackets must close in order"
assert is_balanced("no brackets here") is True, "text with no brackets is balanced"
