assert quality_grade(0.0) == "A", "no nulls at all"
assert quality_grade(0.9) == "A", "just under 1%"
assert quality_grade(1.0) == "B", "exactly 1% is no longer an A"
assert quality_grade(3.2) == "B", "the ordering test — a low-to-high chain gets this wrong"
assert quality_grade(4.9) == "B", "just under 5%"
assert quality_grade(5.0) == "C", "exactly 5% drops to C"
assert quality_grade(7.0) == "C", "under 10%"
assert quality_grade(10.0) == "D", "exactly 10% drops to D"
assert quality_grade(20.0) == "D", "under 25%"
assert quality_grade(25.0) == "F", "exactly 25% is a fail"
assert quality_grade(90.0) == "F", "mostly nulls"

assert len(gate("orders", 12000, 3.2, 4, "").splitlines()) == 6, "six lines in the verdict"
assert gate("orders", 12000, 3.2, 4, "").splitlines()[0] == "Table: orders", "the table name is echoed back"
assert gate("orders", 12000, 3.2, 4, "").splitlines()[1] == "Grade: B", "the grade comes from quality_grade"
assert gate("orders", 12000, 3.2, 4, "").splitlines()[2] == "Freshness: OK", "4 hours old is fresh"
assert gate("orders", 12000, 3.2, 4, "").splitlines()[3] == "Volume: OK", "12000 rows is plenty"
assert gate("orders", 12000, 3.2, 4, "").splitlines()[4] == "Note: none", "an empty note reports none"
assert gate("orders", 12000, 3.2, 4, "").splitlines()[5] == "Verdict: PROMOTE", "healthy on all three counts"

assert gate("clicks", 200, 30.0, 40, "upstream late").splitlines()[1] == "Grade: F", "30% nulls is a fail"
assert gate("clicks", 200, 30.0, 40, "upstream late").splitlines()[2] == "Freshness: STALE", "40 hours is past the limit"
assert gate("clicks", 200, 30.0, 40, "upstream late").splitlines()[3] == "Volume: LOW", "200 rows is under the floor"
assert gate("clicks", 200, 30.0, 40, "upstream late").splitlines()[4] == "Note: upstream late", "the operator's note is shown"
assert gate("clicks", 200, 30.0, 40, "upstream late").splitlines()[5] == "Verdict: QUARANTINE", "nothing about this is healthy"

assert gate("t", 1000, 0.0, 24, "").splitlines()[2] == "Freshness: OK", "exactly 24 hours is still fresh"
assert gate("t", 1000, 0.0, 24, "").splitlines()[3] == "Volume: OK", "exactly 1000 rows is enough"
assert gate("t", 999, 0.0, 1, "").splitlines()[3] == "Volume: LOW", "999 rows is not"
assert gate("t", 999, 0.0, 1, "").splitlines()[5] == "Verdict: QUARANTINE", "a perfect grade cannot rescue low volume"
assert gate("t", 5000, 12.0, 1, "").splitlines()[1] == "Grade: D", "12% nulls"
assert gate("t", 5000, 12.0, 1, "").splitlines()[5] == "Verdict: QUARANTINE", "a D is below the C bar"
assert gate("t", 5000, 9.0, 1, "").splitlines()[5] == "Verdict: PROMOTE", "a C still promotes"
assert gate("t", 5000, 0.0, 1, None).splitlines()[4] == "Note: none", "None means nothing was said — a `== \"\"` check would miss it"

assert route("order.created") == "orders_raw", "an order event"
assert route("order.shipped") == "orders_raw", "both order events share an arm"
assert route("user.signup") == "users_raw", "a user event"
assert route("click") == "events_raw", "a click"
assert route("view") == "events_raw", "both interaction events share an arm"
assert route("something.unknown") == "dead_letter", "anything unrecognised is parked"
assert route("") == "dead_letter", "so is an empty type"
