assert is_balanced("(a[b]{c})") is True, "every bracket closed by its partner"
assert is_balanced("") is True, "nothing to balance"
assert is_balanced("no brackets here") is True, "other characters are ignored"
assert is_balanced("(]") is False, "closed by the wrong partner"
assert is_balanced("(") is False, "opened and never closed"
assert is_balanced(")") is False, "closed but never opened"
assert is_balanced("([)]") is False, "interleaved, not nested"
assert is_balanced("((()))") is True, "deeply nested"
assert is_balanced("{[()]}") is True, "all three kinds nested"

assert unmatched_at("(a[b]{c})") == -1, "nothing wrong"
assert unmatched_at("(]") == 1, "the ] at index 1 is the offender"
assert unmatched_at(")") == 0, "a closer with nothing open"
assert unmatched_at("(") == 0, "an opener never closed points back at itself"
assert unmatched_at("ab(cd") == 2, "wherever it was opened"
assert unmatched_at("([)]") == 2, "the ) comes while [ is still open"
assert unmatched_at("") == -1, "nothing to report"

assert next_bigger([2, 1, 3]) == [3, 3, -1], "3 is next-bigger for both, and nothing follows it"
assert next_bigger([5, 4, 3]) == [-1, -1, -1], "a falling run has no next-bigger anywhere"
assert next_bigger([1, 2, 3]) == [2, 3, -1], "a rising run takes its neighbour"
assert next_bigger([]) == [], "nothing at all"
assert next_bigger([7]) == [-1], "one value"
assert next_bigger([2, 2]) == [-1, -1], "equal is not bigger"
assert next_bigger([30, 8, 25, 19, 40]) == [40, 25, 40, 40, -1], "the stack resolves several at once when 40 arrives"

assert simulate_queue([["a", "b"], ["c"]], 10, 1) == (["a", "b"], 0), "one job per tick, nothing dropped"
assert simulate_queue([["a", "b", "c"]], 10, 3) == (["a", "b", "c"], 0), "three in one tick"
assert simulate_queue([["a", "b", "c"]], 2, 1) == (["a"], 1), "the third arrival is dropped — the queue was full"
assert simulate_queue([[], []], 5, 2) == ([], 0), "idle ticks"
assert simulate_queue([], 5, 2) == ([], 0), "no ticks at all"
assert simulate_queue([["a"]], 0, 1) == ([], 1), "a capacity of zero drops everything"
assert simulate_queue([["a", "b"], []], 10, 1) == (["a", "b"], 0), "the second tick drains what the first left"
assert simulate_queue([["a", "b", "c"], []], 10, 1)[0] == ["a", "b"], "first in, first out — c is still waiting"
